image: condaforge/miniforge3:24.3.0-0

tasks:
  - name: Initialize
    init: |
      . /opt/conda/etc/profile.d/conda.sh
      conda activate base
      sleep 5
      mamba env create --name sizemeup --file /workspace/sizemeup/environment.yml
      conda activate sizemeup
      mamba install -y -c conda-forge -c bioconda just pre-commit
      mkdir -p .vscode
      echo '{"python.pythonPath": "/home/gitpod/.conda/envs/sizemeup/bin/python"}' > .vscode/settings.json
      pre-commit install --install-hooks
      just install
    command: |

vscode:
  extensions:
    - codezombiech.gitignore                # Language support for .gitignore files
    - davidanson.vscode-markdownlint        # Markdown/CommonMark linting and style checking for Visual Studio Code
    - eamodio.gitlens                       # Quickly glimpse into whom, why, and when a line or code block was changed
    - EditorConfig.EditorConfig             # override user/workspace settings with settings found in .editorconfig files
    - Gruntfuggly.todo-tree                 # Display TODO and FIXME in a tree view in the activity bar
    - mechatroner.rainbow-csv               # Highlight columns in csv files in different colors
    - oderwat.indent-rainbow                # Highlight indentation level
    - streetsidesoftware.code-spell-checker # Spelling checker for source code
    - ms-python.black-formatter             # Support for Python Black formatter
    - njpwerner.autodocstring               # Use type hints to auto create doc strings
    - ms-python.python                      # Syntax and linting
